name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea in detail.

  - type: checkboxes
    id: existing-issue
    attributes:
      label: Existing Feature Check
      description: Please confirm you've checked for existing requests
      options:
        - label: I have searched the existing issues and this feature has not been requested
          required: true

  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: Which area does this feature relate to?
      options:
        - Project Generator
        - Code Quality Checker
        - Configuration Manager
        - Development Server
        - CLI Interface
        - Documentation
        - Testing
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: Other approaches I considered...

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe the use case for this feature
      placeholder: |
        As a [type of user], I want [feature] so that [benefit].
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, or screenshots about the feature

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help implement this feature?
      options:
        - label: I would be willing to submit a PR to implement this feature

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
